### ISSUE TITLE
CheckBoxDef causes an error if you don't explicitly set a label

### ISSUE THREAD

**Issue by valadaptive** [AdrianEddy/after-effects#3]
It appears that the API zero-initializes `PF_ParamDef`s, which means that a `CheckBoxDef`'s `nameptr` is null by default.

After Effects doesn't like this, and will give a hard-to-debug "the plugin failed to initialize" error if you don't explicitly set the checkbox's label.

One way to fix this would be to initialize `nameptr` to point to an empty string, but that'd require separating out the initialization code for each type of parameter.

**Comment by AdrianEddy** [comment]
Good catch, fixed
