### ISSUE TITLE
Parameters' UI flags cannot be modified in-place

### ISSUE THREAD

**Issue by valadaptive** [AdrianEddy/after-effects#6]
I have some code which updates whether parameters are disabled during the `UPDATE_PARAMS_UI` callback. The natural way to do this is to loop over the parameters in the passed `Parameters` struct and call `set_ui_flags` on them. However, this causes a crash.

The parameters passed in, at least for this callback, should be considered read-only and must be cloned before being modified. I'm not sure if this applies to all parameters in all callbacks or just certain ones, or if this applies to all parameter properties or just the UI flags. The API should enforce this.

**Comment by AdrianEddy** [comment]
Can you show me a minimal example which crashes?

**Comment by valadaptive** [comment]
See https://github.com/valadaptive/after-effects-crash-repro. It contains code to disable the parameter UI element in response to a `Command::UpdateParamsUi` (note that `OutFlags::SendUpdateParamsUI` has to be set in the PiPL). This will cause a crash if the param is not cloned before `set_ui_flags` is called.

**Comment by valadaptive** [comment]
Also [in the official documentation](https://ae-plugins.docsforadobe.dev/effect-details/parameter-supervision.html):

> During PF_Cmd_UPDATE_PARAMS_UI, you may only change the appearance and enable state of parameters. Use `PF_UpdateParamUI()` from [PF_ParamUtilSuite3](https://ae-plugins.docsforadobe.dev/effect-details/parameter-supervision.html#effect-detals-parameter-supervision-pf-paramutilsuite) to update the UI, passing it a *copy* of the parameter you wish to modify. Do not attempt to modify the original.

**Comment by AdrianEddy** [comment]
It actually correctly panics with 

```
AfterFX.exe ERROR - thread '<unnamed>' panicked at 'Tried to mutably borrow immutable data': D:\...\after-effects\after-effects\src\lib.rs:626
```


there's `params.get_mut()` to get mutable reference, while `params.get()` is read-only. I'm not sure how to enforce that at the compile stage, except splitting `Ownership` to two separate types. Any other ideas?

![image](https://github.com/AdrianEddy/after-effects/assets/3849067/8d3b1e93-77da-44c8-a745-914c73debc74)

**Comment by AdrianEddy** [comment]
When compiled in debug mode (`just build`) instead of release, this panic is also catched and nicely displayed in AE: 
![image](https://github.com/AdrianEddy/after-effects/assets/3849067/6a69a789-5093-4360-9d0b-048426cd8f4b)

**Comment by valadaptive** [comment]
Ooh, I didn't know this library displayed panic messages in debug mode! That's great for dev ergonomics; I'm used to just guessing at random crashes in my previous C iteration of my effect.

Yes, I believe the only way to fix this would be splitting `Ownership` into two types (maybe three--`OwnershipAE`, `OwnershipAEMut`, and `OwnershipRust`). It might result in more boilerplate, but would allow the type system to catch such errors.

I wonder if it's possible to model ownership using something like `PhantomData` in `ParamDef`.

**Comment by valadaptive** [comment]
Just tested it and `get_mut` does indeed work, though I'm not sure if it *should*, given that the documentation says not to modify parameters during the `UpdateParamsUi` callback.

Are there commands (other than `params_setup` which is handled separately) that *do* allow mutable access to params? If not, then `handle_command` could be changed to pass an immutable reference to the parameters.

**Comment by mobile-bungalow** [comment]
If your param is [supervised](https://ae-plugins.docsforadobe.dev/effect-details/parameter-supervision.html?highlight=userchanged#parameter-supervision), I think you can change parameters during `PF_UserChangedParam`. But that's not super useful.

**Comment by AdrianEddy** [comment]
I changed `params.get()` to return `ReadOnlyOwnership` which prevents calling any mutable methods on it, so that case will now not compile. You can modify it after calling `.clone()` on it
